version: '3.8'

services:
  angular-app:
    image: node:14.21.3
    container_name: angular-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm start"
